version: '3.8'

services:
  elf:
    build: .
    container_name: elf-app
    ports:
      - "8501:8501"
    volumes:
      - ./:/app
    environment:
      - PYTHONUNBUFFERED=1
    restart: unless-stopped
